INSERT INTO asset VALUES
(0, 'tempSensor1', (SELECT id FROM network WHERE name = 'home')),
(1, 'tempSensor2', (SELECT id FROM network WHERE name = 'home')),
(2, 'seismicSensor1', (SELECT id FROM network WHERE name = 'home')),
(3, 'automaticScram', (SELECT id FROM network WHERE name = 'home')),
(4, 'operator', (SELECT id FROM network WHERE name = 'home')),
(5, 'controlRodController', (SELECT id FROM network WHERE name = 'home')),
(6, 'controlBlade1', (SELECT id FROM network WHERE name = 'home')),
(7, 'controlBlade2', (SELECT id FROM network WHERE name = 'home')),
(8, 'controlBlade5', (SELECT id FROM network WHERE name = 'home')),
(9, 'controlBlade4', (SELECT id FROM network WHERE name = 'home')),
(10, 'pulseControlRod', (SELECT id FROM network WHERE name = 'home')),
(11, 'buildingCompressedAir', (SELECT id FROM network WHERE name = 'home')),
(12, 'linearPowerSensor', (SELECT id FROM network WHERE name = 'home')),
(13, 'nlogPowerSensor', (SELECT id FROM network WHERE name = 'home')),
(14, 'pulsePowerSensor', (SELECT id FROM network WHERE name = 'home')),
(15, 'controlSystemRecorder', (SELECT id FROM network WHERE name = 'home')),
(16, 'buildingEvacAlarm', (SELECT id FROM network WHERE name = 'home')),
(17, 'beamRoomScramChain', (SELECT id FROM network WHERE name = 'home')),
(18, 'highFluxMonitor', (SELECT id FROM network WHERE name = 'home')),
(19, 'periodSensor', (SELECT id FROM network WHERE name = 'home')),
(20, 'logNHVFailureSensor', (SELECT id FROM network WHERE name = 'home')),
(21, 'CICHVFailureSensor', (SELECT id FROM network WHERE name = 'home')),
(22, 'continuousAirMonitor', (SELECT id FROM network WHERE name = 'home')),
(23, 'areaMonitoringSystem', (SELECT id FROM network WHERE name = 'home')),
(24, 'diffuser', (SELECT id FROM network WHERE name = 'home')),
(25, 'coolantLevelSensor', (SELECT id FROM network WHERE name = 'home')),
(26, 'backupPower', (SELECT id FROM network WHERE name = 'home')),
(27, 'recirculationPump', (SELECT id FROM network WHERE name = 'home')),
(28, 'flowmeter', (SELECT id FROM network WHERE name = 'home')),
(29, 'conductivityCell1', (SELECT id FROM network WHERE name = 'home')),
(30, 'conductivityCell2', (SELECT id FROM network WHERE name = 'home')),
(31, 'ionExchanger', (SELECT id FROM network WHERE name = 'home')),
(32, 'poolTotalizer', (SELECT id FROM network WHERE name = 'home')),
(33, 'coolantTempSensor', (SELECT id FROM network WHERE name = 'home')),
(34, 'heatExchangePump1', (SELECT id FROM network WHERE name = 'home')),
(35, 'heatExchangePump2', (SELECT id FROM network WHERE name = 'home')),
(36, 'leakDetector', (SELECT id FROM network WHERE name = 'home')),
(37, 'towerTotalizer', (SELECT id FROM network WHERE name = 'home')),
(38, 'ventilationController', (SELECT id FROM network WHERE name = 'home')),
(39, 'ventilationIntakeFan', (SELECT id FROM network WHERE name = 'home')),
(40, 'ventilationOuttakeFan', (SELECT id FROM network WHERE name = 'home')),
(41, 'ventilationAirDetector', (SELECT id FROM network WHERE name = 'home')),
(42, 'ventilationDampers', (SELECT id FROM network WHERE name = 'home')),
(43, 'ventilationDiluteFan', (SELECT id FROM network WHERE name = 'home')),
(44, 'reactor', (SELECT id FROM network WHERE name = 'home')),
(45, 'coolant', (SELECT id FROM network WHERE name = 'home')),
(46, 'airborneRadiation', (SELECT id FROM network WHERE name = 'home')),
(47, 'buildingPower', (SELECT id FROM network WHERE name = 'home')),
(48, 'seismicActivity', (SELECT id FROM network WHERE name = 'home'))

ON CONFLICT DO NOTHING;

INSERT INTO quality VALUES
(0, 'status', '=', 'ok'),
(1, 'status', '=', 'ok'),
(0, 'temp', '=', '310'),
(1, 'temp', '=', '278'),
(0, 'calibration', '=', 'normal'),
(1, 'calibration', '=', 'normal'),
(0, 'powerStatus', '=', 'on'),
(1, 'powerStatus', '=', 'on'),
(0, 'platform', '=', 'tempSensor'),
(1, 'platform', '=', 'tempSensor'),
(2, 'status', '=', 'ok'),
(2, 'powerStatus', '=', 'on'),
(2, 'magnitude', '=', '.001'),
(2, 'platform', '=', 'seismicSensor'),
(3, 'status', '=', 'ok'),
(3, 'powerStatus', '=', 'on'),
(3, 'mode', '=', 'manual'),
(3, 'activated', '=', 'false'),
(3, 'platform', '=', 'scramUnit'),
(4, 'status', '=', 'ok'),
(4, 'powerStatus', '=', 'on'),
(4, 'manualScram', '=', 'false'),
(4, 'operationMode', '=', 'manual'),
(4, 'platform', '=', 'operatorStation'),
(5, 'status', '=', 'ok'),
(5, 'powerStatus', '=', 'on'),
(5, 'emagPower', '=', 'on'),
(5, 'platform', '=', 'controlRodController'),
(6, 'motorStatus', '=', 'ok'),
(7, 'motorStatus', '=', 'ok'),
(9, 'motorStatus', '=', 'ok'),
(9, 'motorStatus', '=', 'ok'),
(8, 'motorStatus', '=', 'ok'),
(6, 'actualPosition', '=', '1.5'),
(7, 'actualPosition', '=', '1.5'),
(8, 'actualPosition', '=', '1.5'),
(9, 'actualPosition', '=', '1.5'),
(6, 'reportedPosition', '=', '1.5'),
(7, 'reportedPosition', '=', '1.5'),
(8, 'reportedPosition', '=', '1.5'),
(9, 'reportedPosition', '=', '1.5'),
(10, 'actualPosition', '=', '0'),
(10, 'cylinderPosition', '=', '0'),
(10, 'reportedPosition', '=', '0'),
(10, 'pulsed', '=', 'false'),
(6, 'platform', '=', 'controlBlade'),
(7, 'platform', '=', 'controlBlade'),
(8, 'platform', '=', 'controlBlade'),
(9, 'platform', '=', 'controlBlade'),
(10, 'platform', '=', 'pulseControlRod'),
(11, 'status', '=', 'ok'),
(11, 'powerStatus', '=', 'on'),
(11, 'compressor', '=', 'on'),
(11, 'ctValve', '=', 'closed'),
(11, 'tankPressure', '=', '10'),
(11, 'platform', '=', 'airCompressor'),
(12, 'status', '=', 'ok'),
(12, 'powerStatus', '=', 'on'),
(12, 'powerLevel', '=', '0.1'),
(12, 'platform', '=', 'powerSensor'),
(13, 'status', '=', 'ok'),
(13, 'powerStatus', '=', 'on'),
(13, 'powerLevel', '=', '0.1'),
(13, 'platform', '=', 'powerSensor'),
(14, 'status', '=', 'ok'),
(14, 'powerStatus', '=', 'on'),
(14, 'powerLevel', '=', '0.1'),
(14, 'platform', '=', 'powerSensor'),
(15, 'status', '=', 'ok'),
(15, 'powerStatus', '=', 'on'),
(15, 'dataValid', '=', 'true'),
(15, 'platform', '=', 'controlSystemRecorder'),
(16, 'status', '=', 'ok'),
(16, 'powerStatus', '=', 'on'),
(16, 'activated', '=', 'false'),
(16, 'platform', '=', 'evacuationAlarm'),
(17, 'status', '=', 'ok'),
(17, 'powerStatus', '=', 'on'),
(17, 'activated', '=', 'false'),
(17, 'platform', '=', 'scramInput'),
(18, 'status', '=', 'ok'),
(18, 'powerStatus', '=', 'on'),
(18, 'alarmActivated', '=', 'false'),
(18, 'platform', '=', 'fluxMonitor'),
(19, 'status', '=', 'ok'),
(19, 'powerStatus', '=', 'on'),
(19, 'output', '=', 'normal'),
(19, 'platform', '=', 'periodSensor'),
(20, 'status', '=', 'ok'),
(20, 'powerStatus', '=', 'on'),
(20, 'activated', '=', 'false'),
(21, 'status', '=', 'ok'),
(21, 'powerStatus', '=', 'on'),
(21, 'activated', '=', 'false'),
(21, 'platform', '=', 'HVSensor'),
(20, 'platform', '=', 'HVSensor'),
(22, 'status', '=', 'ok'),
(22, 'powerStatus', '=', 'on'),
(22, 'airborneRadiation', '=', 'low'),
(22, 'platform', '=', 'CAM'),
(23, 'status', '=', 'ok'),
(23, 'powerStatus', '=', 'on'),
(23, 'N16_level', '=', '0'),
(23, 'platform', '=', 'N16Detector'),
(24, 'status', '=', 'ok'),
(24, 'powerStatus', '=', 'on'),
(24, 'platform', '=', 'diffuser'),
(25, 'status', '=', 'ok'),
(25, 'powerStatus', '=', 'on'),
(25, 'level', '=', '0.0'),
(25, 'platform', '=', 'coolantLevelSensor'),
(26, 'status', '=', 'ok'),
(26, 'chargeLevel', '=', '1'),
(26, 'platform', '=', 'backupPower'),
(27, 'status', '=', 'ok'),
(27, 'powerStatus', '=', 'on'),
(27, 'platform', '=', 'pump'),
(28, 'status', '=', 'ok'),
(28, 'powerStatus', '=', 'on'),
(28, 'flowRate', '=', '10'),
(28, 'platform', '=', 'flowmeter'),
(29, 'status', '=', 'ok'),
(29, 'powerStatus', '=', 'on'),
(29, 'resistance', '=', '18.2'),
(30, 'status', '=', 'ok'),
(30, 'powerStatus', '=', 'on'),
(30, 'resistance', '=', '18.5'),
(29, 'platform', '=', 'conductivitySensor'),
(30, 'platform', '=', 'conductivitySensor'),
(31, 'status', '=', 'ok'),
(31, 'platform', '=', 'ionExchanger'),
(32, 'status', '=', 'ok'),
(32, 'platform', '=', 'totalizer'),
(33, 'status', '=', 'ok'),
(33, 'powerStatus', '=', 'on'),
(33, 'temp', '=', '330'),
(33, 'platform', '=', 'coolantTempSensor'),
(34, 'status', '=', 'ok'),
(34, 'powerStatus', '=', 'on'),
(35, 'status', '=', 'ok'),
(35, 'powerStatus', '=', 'on'),
(34, 'platform', '=', 'pump'),
(35, 'platform', '=', 'pump'),
(36, 'status', '=', 'ok'),
(36, 'powerStatus', '=', 'on'),
(36, 'resistance', '=', '18.2'),
(36, 'leakDetected', '=', 'false'),
(36, 'platform', '=', 'conductivitySensor'),
(37, 'status', '=', 'ok'),
(37, 'platform', '=', 'totalizer'),
(38, 'status', '=', 'ok'),
(38, 'powerStatus', '=', 'on'),
(38, 'mode', '=', 'normal'),
(38, 'platform', '=', 'ventilationController'),
(39, 'status', '=', 'ok'),
(39, 'powerStatus', '=', 'on'),
(39, 'fan', '=', 'on'),
(39, 'platform', '=', 'fan'),
(40, 'status', '=', 'ok'),
(40, 'powerStatus', '=', 'on'),
(40, 'fan', '=', 'on'),
(40, 'platform', '=', 'fan'),
(41, 'status', '=', 'ok'),
(41, 'powerStatus', '=', 'on'),
(41, 'Ar41_level', '=', '0.0'),
(41, 'platform', '=', 'Ar41Detector'),
(42, 'status', '=', 'ok'),
(42, 'powerStatus', '=', 'on'),
(42, 'dampers', '=', 'open'),
(42, 'platform', '=', 'dampers'),
(43, 'status', '=', 'ok'),
(43, 'powerStatus', '=', 'on'),
(43, 'fan', '=', 'on'),
(43, 'platform', '=', 'fan'),
(44, 'fuelTemp', '=', '330'),
(44, 'reactorPower', '=', '0.1'),
(45, 'coolantLevel', '=', '0.0'),
(45, 'coolantTemp', '=', '330'),
(46, 'airborneFissionProducts', '=', 'low'),
(46, 'N16_level', '=', '0'),
(46, 'Ar41_level', '=', '0'),
(47, 'buildingPower', '=', 'on'),
(48, 'seismicActivity', '=', '2.4'),
(44, 'platform', '=', 'physical'),
(45, 'platform', '=', 'physical'),
(46, 'platform', '=', 'physical'),
(47, 'platform', '=', 'physical'),
(9, 'platform', '=', 'controlBlade')

ON CONFLICT DO NOTHING;

INSERT INTO topology VALUES
(0, 3, '->', 'connected_modbus_slave', '', ''),
(1, 3, '->', 'connected_modbus_slave', '', ''),
(0, 15, '->', 'connected_modbus_slave', '', ''),
(1, 15, '->', 'connected_modbus_slave', '', ''),
(0, 4, '->', 'connected_modbus_slave', '', ''),
(1, 4, '->', 'connected_modbus_slave', '', ''),
(44, 0, '->', 'physical', '', ''),
(44, 1, '->', 'physical', '', ''),
(47, 0, '->', 'power', '=', '120'),
(47, 1, '->', 'power', '=', '120'),
(2, 3, '->', 'connected_modbus_slave', '', ''),
(48, 2, '->', 'physical', '', ''),
(47, 2, '->', 'power', '=', '120'),
(3, 5, '->', 'connected_emag_power', '', ''),
(3, 0, '->', 'connected_modbus_master', '', ''),
(3, 1, '->', 'connected_modbus_master', '', ''),
(3, 2, '->', 'connected_modbus_master', '', ''),
(3, 18, '->', 'connected_modbus_master', '', ''),
(3, 16, '->', 'connected_modbus_master', '', ''),
(3, 17, '->', 'connected_modbus_master', '', ''),
(3, 20, '->', 'connected_modbus_master', '', ''),
(3, 21, '->', 'connected_modbus_master', '', ''),
(3, 4, '->', 'connected_modbus_master', '', ''),
(47, 3, '->', 'power', '=', '120'),
(4, 3, '->', 'connected_modbus_slave', '', ''),
(4, 15, '->', 'connected_ethernet', '', ''),
(4, 25, '->', 'connected_modbus_master', '', ''),
(4, 33, '->', 'connected_modbus_master', '', ''),
(4, 5, '->', 'connected_modbus_master', '', ''),
(4, 16, '->', 'connected_modbus_master', '', ''),
(4, 0, '->', 'connected_modbus_master', '', ''),
(4, 1, '->', 'connected_modbus_master', '', ''),
(4, 12, '->', 'connected_modbus_master', '', ''),
(4, 13, '->', 'connected_modbus_master', '', ''),
(4, 14, '->', 'connected_modbus_master', '', ''),
(4, 22, '->', 'connected_modbus_master', '', ''),
(4, 19, '->', 'connected_modbus_master', '', ''),
(4, 23, '->', 'connected_modbus_master', '', ''),
(4, 41, '->', 'connected_modbus_master', '', ''),
(4, 28, '->', 'connected_modbus_master', '', ''),
(4, 29, '->', 'connected_modbus_master', '', ''),
(4, 30, '->', 'connected_modbus_master', '', ''),
(4, 34, '->', 'connected_modbus_master', '', ''),
(4, 35, '->', 'connected_modbus_master', '', ''),
(4, 36, '->', 'connected_modbus_master', '', ''),
(47, 4, '->', 'power', '=', '120'),
(5, 4, '->', 'connected_modbus_slave', '', ''),
(5, 11, '->', 'connected_modbus_master', '', ''),
(47, 5, '->', 'power', '=', '120'),
(6, 5, '->', 'subcomponent', '', ''),
(7, 5, '->', 'subcomponent', '', ''),
(8, 5, '->', 'subcomponent', '', ''),
(9, 5, '->', 'subcomponent', '', ''),
(10, 5, '->', 'subcomponent', '', ''),
(11, 5, '->', 'connected_modbus_slave', '', ''),
(11, 10, '->', 'pneumatic_closed', '', ''),
(47, 11, '->', 'power', '=', '120'),
(12, 18, '->', 'connected_modbus_slave', '', ''),
(12, 15, '->', 'connected_modbus_slave', '', ''),
(12, 4, '->', 'connected_modbus_slave', '', ''),
(44, 12, '->', 'physical', '', ''),
(47, 12, '->', 'power', '=', '120'),
(13, 4, '->', 'connected_modbus_slave', '', ''),
(44, 13, '->', 'physical', '', ''),
(47, 13, '->', 'power', '=', '120'),
(14, 4, '->', 'connected_modbus_slave', '', ''),
(44, 14, '->', 'physical', '', ''),
(47, 14, '->', 'power', '=', '120'),
(15, 0, '->', 'connected_modbus_master', '', ''),
(15, 1, '->', 'connected_modbus_master', '', ''),
(15, 12, '->', 'connected_modbus_master', '', ''),
(47, 15, '->', 'power', '=', '120'),
(16, 23, '->', 'connected_modbus_master', '', ''),
(16, 25, '->', 'connected_modbus_master', '', ''),
(16, 4, '->', 'connected_modbus_slave', '', ''),
(16, 3, '->', 'connected_modbus_slave', '', ''),
(47, 16, '->', 'power', '=', '120'),
(17, 3, '->', 'connected_modbus_slave', '', ''),
(47, 17, '->', 'power', '=', '120'),
(18, 12, '->', 'connected_modbus_master', '', ''),
(18, 3, '->', 'connected_modbus_slave', '', ''),
(47, 18, '->', 'power', '=', '120'),
(19, 4, '->', 'connected_modbus_slave', '', ''),
(47, 19, '->', 'power', '=', '120'),
(20, 3, '->', 'connected_modbus_slave', '', ''),
(21, 3, '->', 'connected_modbus_slave', '', ''),
(47, 20, '->', 'power', '=', '120'),
(47, 21, '->', 'power', '=', '120'),
(22, 4, '->', 'connected_modbus_slave', '', ''),
(22, 38, '->', 'connected_modbus_slave', '', ''),
(46, 22, '->', 'physical', '', ''),
(47, 22, '->', 'power', '=', '120'),
(23, 16, '->', 'connected_modbus_slave', '', ''),
(23, 4, '->', 'connected_modbus_slave', '', ''),
(46, 23, '->', 'physical', '', ''),
(47, 23, '->', 'power', '=', '120'),
(47, 24, '->', 'power', '=', '120'),
(25, 4, '->', 'connected_modbus_slave', '', ''),
(25, 16, '->', 'connected_modbus_slave', '', ''),
(45, 25, '->', 'physical', '', ''),
(47, 25, '->', 'power', '=', '120'),
(26, 16, '->', 'power', '=', '0.0'),
(26, 23, '->', 'power', '=', '0.0'),
(26, 25, '->', 'power', '=', '0'),
(26, 2, '->', 'power', '=', '1.0'),
(47, 26, '->', 'power', '=', '120'),
(27, 4, '->', 'connected_modbus_slave', '', ''),
(45, 27, '->', 'physical', '', ''),
(47, 27, '->', 'power', '=', '120'),
(28, 4, '->', 'connected_modbus_slave', '', ''),
(45, 28, '->', 'physical', '', ''),
(47, 28, '->', 'power', '=', '120'),
(29, 4, '->', 'connected_modbus_slave', '', ''),
(30, 4, '->', 'connected_modbus_slave', '', ''),
(45, 29, '->', 'physical', '', ''),
(45, 30, '->', 'physical', '', ''),
(47, 29, '->', 'power', '=', '120'),
(47, 30, '->', 'power', '=', '120'),
(45, 31, '->', 'physical', '', ''),
(45, 32, '->', 'physical', '', ''),
(33, 4, '->', 'connected_modbus_slave', '', ''),
(45, 33, '->', 'physical', '', ''),
(47, 33, '->', 'power', '=', '120'),
(34, 4, '->', 'connected_modbus_slave', '', ''),
(35, 4, '->', 'connected_modbus_slave', '', ''),
(45, 34, '->', 'physical', '', ''),
(45, 35, '->', 'physical', '', ''),
(47, 34, '->', 'power', '=', '120'),
(47, 35, '->', 'power', '=', '120'),
(36, 4, '->', 'connected_modbus_slave', '', ''),
(45, 36, '->', 'physical', '', ''),
(47, 36, '->', 'power', '=', '120'),
(45, 37, '->', 'physical', '', ''),
(38, 39, '->', 'connected_modbus_master', '', ''),
(38, 40, '->', 'connected_modbus_master', '', ''),
(38, 43, '->', 'connected_modbus_master', '', ''),
(38, 22, '->', 'connected_modbus_master', '', ''),
(38, 4, '->', 'connected_modbus_slave', '', ''),
(47, 38, '->', 'power', '=', '120'),
(39, 38, '->', 'connected_modbus_slave', '', ''),
(47, 39, '->', 'power', '=', '120'),
(40, 38, '->', 'connected_modbus_slave', '', ''),
(47, 40, '->', 'power', '=', '120'),
(41, 4, '->', 'connected_modbus_slave', '', ''),
(47, 41, '->', 'power', '=', '120'),
(46, 41, '->', 'physical', '', ''),
(42, 38, '->', 'connected_modbus_slave', '', ''),
(47, 42, '->', 'power', '=', '120'),
(43, 38, '->', 'connected_modbus_slave', '', ''),
(47, 5, '->', 'power', '=', '120')

ON CONFLICT DO NOTHING;
